Authentication/urls.py
from django.urls import path
from . import views

app_name = 'Authentication'

urlpatterns = [
	path('login/', views.ManageUserLoginView, name="login"),
	path('logout/', views.ManageUserLogoutView, name="logout"),
	path('register/', views.ManageUserRegisterView, name="register"),
	path('profile/', views.ManageUserProfileView, name="profile"),
	path('send-mail/', views.ManageEmailConfirmationView, name="email"),
]

EComerce/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include("Products.urls", namespace = 'products')),
    path('auth/' , include("Authentication.urls", namespace = 'auth')),
]

Authentication/models.py
from django.db import models
from django.contrib.auth.models import User

class PublicUsers(models.Model):
    user = models.ForeignKey(User , on_delete=models.PROTECT)
    contact = models.IntegerField()
    address = models.CharField(max_length=250)
    date = models.DateField(auto_now=True)
    def __str__(self):
        return "{}".format(self.user)

Authentication/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from Authentication.models import PublicUsers

class ManageCreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = [
			'username',
			'email',
			'password1',
			'password2',
			]

class ManagePublicUsersForm(forms.ModelForm):
	class Meta:
		model = PublicUsers
		fields = [
			'user' ,
			'contact' ,
			'address' ,
		]

Authentication/views.py
from re import A
from unicodedata import name
from django.shortcuts import render, redirect , get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from .user_handeling import unauthenticated_user
from .forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
import random

def ManageUserLoginView(LoginView):
	if LoginView.method == 'POST':
		username = LoginView.POST.get('username')
		password =LoginView.POST.get('password')
		user = authenticate(LoginView, username=username, password=password)
		if user is not None:
			login(LoginView, user)
			return redirect('auth:profile')
		else:
			context = {
				'msg' : 'Username Or Password Is Incorrect',
			}
			return render(LoginView , 'Authentication/Login.html' , context)
	else:
		return render(LoginView , 'Authentication/Login.html')

@login_required(login_url='auth:login')
def ManageUserLogoutView(request):
	logout(request)
	return redirect('products:listview')

@unauthenticated_user
def ManageUserRegisterView(RegisterView):
	form = ManageCreateUserForm()
	if RegisterView.method == 'POST':
		form = ManageCreateUserForm({
			'username' : RegisterView.POST.get('u-name') ,
			'email' : RegisterView.POST.get('email') ,
			'password1' : RegisterView.POST.get('password1') ,
			'password2' : RegisterView.POST.get('password2') ,
		})
		if form.is_valid():
			user = form.save()
			
			send_mail(
				'This Email Has Been Redistered',
				'This Email Has Been Redistered On An E-Commerce Website',
				'ztapp000@gmail.com',
				[str(RegisterView.POST.get('email'))],
				fail_silently=True,
			)
			username = form.cleaned_data.get('username')
			group = Group.objects.get(name='Public')
			user.groups.add(group)
			messages.success(RegisterView, 'Account was created for ' + username)
			return redirect('auth:profile')
		else:
			if str(RegisterView.POST.get('u-name')) in [i.username for i in User.objects.all()]:
				msg1 = "User With This Username Already Exist"
			if str(RegisterView.POST.get('password1')) == str(RegisterView.POST.get('password2')):
				msg2 = "Passwords Does Not Match"
			context = {
				'msg1': msg1 ,
				'msg2': msg2 ,
				'form': form ,
				}
			return render(RegisterView, 'Authentication/Register.html', context)
	else:
		context = {
			'form' : ManageCreateUserForm() ,
		}
		return render(RegisterView , 'Authentication/Register.html', context)

@login_required(login_url='auth:login')
def ManageEmailConfirmationView(EmailView):
	if EmailView.method == 'POST':
		code = ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f']
		random.shuffle(code)
		confirmation = ""
		for i in range(1,9):
			confirmation = confirmation + code[i]
		if str(EmailView.POST.get('email')) != str(EmailView.user.email):
			send_mail(
				'Confirm Email Code',
				'This Email Has Been Updated On An E-Commerce Website. \n Confirmation Code is : {}'.format(confirmation),
				'ztapp000@gmail.com',
				[str(EmailView.POST.get('email'))],
				fail_silently=True,
			)
	EmailView.session['confirmation'] = confirmation
	print(EmailView.session.get('confirmation'))
	return render(EmailView , 'Authentication/Profile.html')
		

@login_required(login_url='auth:login')
def ManageUserProfileView(ProfileView):
	if ProfileView.method == 'POST':
		try:
			instance = get_object_or_404(PublicUsers , user = ProfileView.user)
		except:
			instance = None
		publicuserform = ManagePublicUsersForm({
			'user' : ProfileView.user ,
			'contact' : ProfileView.POST.get('contact') ,
			'address' : ProfileView.POST.get('address') ,
		} or None , instance = instance )
		publicuserform.save()
		if str(ProfileView.POST.get('email')) != str(ProfileView.user.email):
			if ProfileView.POST.get('code') == ProfileView.session.get('confirmation'):
				previous_email = ProfileView.user.email
				ProfileView.user.email = ProfileView.POST.get('email')
				ProfileView.user.save()
				send_mail(
					'This Email Has Been Updated',
					'This Email Has Been Updated On An E-Commerce Website. \n Previous Email Was {}'.format(previous_email),
					'ztapp000@gmail.com',
					[str(ProfileView.POST.get('email'))],
					fail_silently=True,
				)
		form = ManagePublicUsersForm(get_object_or_404(PublicUsers , user = ProfileView.user))
		context = {
			'form' : form ,
		}
		return render(ProfileView , 'Authentication/Profile.html')
	else:
		try:
			form = ManagePublicUsersForm(instance = get_object_or_404(PublicUsers , user = ProfileView.user))
		except:
			form = ManagePublicUsersForm()
		context = {
			'form' : form ,
		}
		return render(ProfileView , 'Authentication/Profile.html' , context)
# @admin_only
# @login_required(login_url='main_login')
# @allowed_users(allowed_roles=['admin'])

Authentication/templates/Authentication/Login.html
{% extends 'MainPage.html' %}
{% block content %}

    <div style="width:50%;text-align:center;background-color: #7d6969;margin:auto;padding:20px;">
        <h3>Login</h3>

        <span>
            {% if msg %}
                {{ msg | safe }}
            {% else %}
                Add your credentials
            {% endif %}
        </span>
        <form method="POST" >
            <table style="width:100% ;">
                <tbody style="background-color:rgb(163, 162, 162) ;">
                    <tr style="height: 55px">
                        <td>Username</td>
                        <td><input type="text" name="username" placeholder="Username" style="width:80%;" required id="id_username"></td>
                    </tr>
                    <tr style="height: 55px">
                        <td>Password</td>
                        <td><input type="password" name="password" placeholder="Password" style="width:80%;" required id="id_password"></td>
                    </tr>
                </tbody>
            </table>
            
            <button type="submit" name="login" class="btn btn-primary shadow-2 mb-4">Login</button>
            {% csrf_token %}

        </form>
    </div>
{% endblock %}

Authentication/templates/Authentication/Profile.html
{% extends 'MainPage.html' %}
{% block content %}
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <div style="width:50%;text-align:center;background-color: #7d6969;margin:auto;padding:20px;">
        <h3>Profile</h3>
        <table style="width:100% ;">
            <tbody style="background-color:rgb(163, 162, 162) ;">
                <tr style="height: 55px">
                    <td>User</td>
                    <td><input type="text" name="user" placeholder="User" style="width:80%;" value="{{ request.user }}" required id="id_user" readonly></td>
                </tr>
                <tr style="height: 55px">
                    <td>Email</td>
                    <td id="email"><input type="email" name="email" placeholder="Email" style="width:67%;" required id="id_email" value="{% if request.user.email %}{{ request.user.email }}{% endif %}"><button onclick="send_mail()" type="button">Send Code</button></td>
                    <td id="confirm" style="display:none"><input name="code" type="text" required id="id_code"></td>
                </tr>
                <tr style="height: 55px">
                    <td>Contact</td>
                    <td><input type="number" name="contact" placeholder="Contact" style="width:80%;" required id="id_contact" value="{% if form.contact.value %}{{ form.contact.value }}{% endif %}"></td>
                </tr>
                <tr style="height: 55px">
                    <td>Address</td>
                    <td><input type="text" name="address" placeholder="Address" style="width:80%;" required id="id_address" value="{% if form.address.value %}{{ form.address.value }}{% endif %}"></td>
                </tr>
            </tbody>
        </table>
        {% csrf_token %}
        <button type="submit" onclick="submitform()" name="submit">Update</button>
    </div>
    <script>
        function submitform() {
            $.ajax({
                type:'POST',
                url:"{% url 'auth:profile' %}",
                data:
                {
                    email:$("#id_email").val(),
                    contact:$("#id_contact").val(),
                    address:$("#id_address").val(),
                    code:$("#id_code").val(),
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                },
                success:function(){
                    alert('User Data Changed Successfully');
                    document.getElementById('email').style.display = 'block'
                    document.getElementById('confirm').style.display = 'none'
                }
            })
        };
        function send_mail() {
            $.ajax({
                type:'POST',
                url:"{% url 'auth:email' %}",
                data:
                {
                    email:$("#id_email").val(),
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                },
                success:function(){
                    alert('Email Sent Successfully');

                    document.getElementById('email').style.display = 'none'
                    document.getElementById('confirm').style.display = 'block'
                }
            })
        }
    </script>
{% endblock %}

Authentication/templates/Authentication/Register.html
{% extends 'MainPage.html' %}
{% block content %}

    <div style="width:50%;text-align:center;background-color: #7d6969;margin:auto;padding:20px;">
        <h3>Register</h3>
        {% if msg1 %}
            {{ msg1 | safe }}
            <br><br>
        {% endif %}
        {% if msg2 %}
            {{ msg2 | safe }}
            <br><br>
        {% endif %}
        <form method="POST">
            <table style="width:100% ;">
                <tbody style="background-color:rgb(163, 162, 162) ;">
                    <tr style="height: 55px">
                        <td>Username</td>
                        <td><input type="text" name="u-name" placeholder="Username" style="width:80%;" required id="id_uname"></td>
                    </tr>
                    <tr style="height: 55px">
                        <td>Email</td>
                        <td><input type="email" name="email" placeholder="Email" style="width:80%;" required id="id_email" ></td>
                    </tr>
                    <tr style="height: 55px">
                        <td>Password</td>
                        <td><input type="password" name="password1" placeholder="Password" style="width:80%;" required id="id_password1"></td>
                    </tr>
                    <tr style="height: 55px">
                        <td>Confirm Password</td>
                        <td><input type="password" name="password2" placeholder="Password" style="width:80%;" required id="id_password2"></td>
                    </tr>
                </tbody>
            </table>
            
            <button type="submit" name="login" class="btn btn-primary shadow-2 mb-4">Register</button>
            {% csrf_token %}

        </form>
    </div>
{% endblock %}