EComerce/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include("Products.urls", namespace = 'products')),
    path('auth/' , include("Authentication.urls", namespace = 'auth')),
]

Products/urls.py
from django.urls import path

from .views import *

app_name = 'Products'

urlpatterns = [
    path('' , ManageProductListView , name="listview" ),
    path('product/<id>' , ManageProductDetailView , name="detailview" ),
    path('category/' , ManageCategoryView , name="category" ),
    path('category/<id>' , ManageCategoryView , name="category" ),
    path('cart/<id>' , ManageAddToCartView , name="cart_add" ),
    path('my-cart/' , ManageCartDetailView , name="cart_detail" ),
    path('my-cart/remove/<id>' , ManageCartRemoveView , name="cart_remove" ),
    path('my-cart/checkout' , ManageCheckoutView , name="cart_checkout" ),
]

Products/models.py
from distutils.sysconfig import customize_compiler
from django.db import models


class Categories(models.Model):
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank = True, null=True)
    name = models.CharField(max_length = 50)
    slug = models.SlugField(max_length=200)
    class Meta:
        unique_together = ('slug', 'parent',)    
        verbose_name_plural = "categories"
    def __str__(self):
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' -> '.join(full_path[::-1])  

class Products(models.Model):
    name = models.CharField(max_length = 50)
    picture = models.URLField()
    category = models.ForeignKey(Categories , on_delete = models.PROTECT)
    price = models.IntegerField()
    available = models.BooleanField()
    def __str__(self):
        return self.name

class Order(models.Model):
    customer = models.CharField(max_length=50)
    address = models.CharField(max_length=500)
    contact = models.IntegerField()
    total_price = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.customer

class OrderProducts(models.Model):
    order = models.ForeignKey(Order , on_delete=models.PROTECT)
    product = models.ForeignKey(Products , on_delete=models.PROTECT)
    qty = models.IntegerField()
    unit_price = models.IntegerField()
    def __str__(self):
        return "{}".format(self.order)

Products/forms.py
from django import forms

from Products.models import Order, OrderProducts

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'customer',
            'address',
            'contact',
            'total_price',
        ]

class OrderProductsCreateForm(forms.ModelForm):
    class Meta:
        model = OrderProducts
        fields = [
            'order',
            'product',
            'qty',
            'unit_price',
        ]

Products/views.py
from itertools import product
from django.shortcuts import render , redirect , get_object_or_404
import time
from Products.models import Categories, Products
from .forms import *
from .cart import *

def get_category():
    v = []
    for i in Categories.objects.all():
        parent = []
        if not i.parent:
            ch1 = []
            for k in i.children.all():
                ch2 = []
                for p in k.children.all():
                    ch3 = []
                    for q in p.children.all():
                        ch4 = []
                        for r in q.children.all():
                            ch4.append({'name': r})
                        if ch4 is not []:
                            ch3.append({'name': q , 'children' : ch4})
                    if ch3 is not []:
                        ch2.append({'name':p , 'children' : ch3})
                if ch2 is not []:
                    ch1.append({'name':k,'children':ch2})
            parent.append({'name':i,'children':ch1})
            v.append(parent)
    return v

def ManageProductListView(ListView):
    products = Products.objects.all()
    context = {
        'categories' : get_category() ,
        'products' : products ,
    }
    return render(ListView , 'Product/List.html' , context)

def ManageProductDetailView(DetailView , id):
    product = get_object_or_404(Products , pk = id)
    context = {
        'categories' : get_category() ,
        'product' : product ,
    }
    return render(DetailView , 'Product/Detail.html' , context)

def ManageCategoryView(CategoryView , id = None):
    categories = Categories.objects.all()
    if id:
        products = Products.objects.all().filter(category = get_object_or_404(Categories , pk = id))
    else:
        try:
            products = Products.objects.all().filter(category = CategoryView.POST.get('category'))
        except:
            return redirect('products:listview')
    context = {
        'categories' : get_category() ,
        'products' : products ,
    }
    return render(CategoryView , 'Product/List.html' , context)

def ManageAddToCartView(AddView , id):
    cart = Cart(AddView)
    product = get_object_or_404(Products, pk=id)
    form = CartAddProductForm(AddView.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],update_quantity=cd['update'])
    time.sleep(1)
    return redirect('products:cart_detail',)

def ManageCartDetailView(DetailView):
    unorder_cart = Cart(DetailView)
    for item in unorder_cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
    cart = []
    for v in unorder_cart:
        quantity = (v.get('update_quantity_form'))
        t_price = (v.get('total_price'))
        price = (v.get('price'))
        product = (v.get('product'))
        cart.append({'product' : product , 'quantity' : quantity , 'price' : price , 't_price' : t_price })
    grand_total = (unorder_cart.get_total_price())
    context = {
        'cart': cart,
        'grand_total': grand_total,
    }
    return render(DetailView, 'Cart/Cart.html',context)

def ManageCartRemoveView(request, id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=id)
    cart.remove(product)
    return redirect('products:cart_detail')

def ManageCheckoutView(CheckoutView):
    unorder_cart = Cart(CheckoutView)
    if CheckoutView.method == 'POST':
        form = OrderCreateForm({
            'customer' : CheckoutView.POST.get('customer') ,
            'address' : CheckoutView.POST.get('address') ,
            'contact' : CheckoutView.POST.get('contact') ,
            'total_price' : unorder_cart.get_total_price() ,
        })
        order = form.save()
        for v in unorder_cart:
            quantity = (v.get('quantity'))
            price = (v.get('price'))
            product = (v.get('product'))
            form = OrderProductsCreateForm({
                'order' : order ,
                'product' : product ,
                'qty' : quantity ,
                'unit_price' : price ,
            })
            if form.is_valid:
                form.save()
        unorder_cart.clear()
        return redirect('products:cart_detail')
    else:
        grand_total = (unorder_cart.get_total_price())
        context = {
            'grand_total': grand_total,
        }
        return render(CheckoutView , 'Cart/Checkout.html' , context)

Products/templates/Cart/Cart.html
{% extends "MainPage.html" %}
{% load static %}
{% block content %}
    <div style="width:50%;text-align:center;background-color: #7d6969;margin:auto;padding:20px;">
        {% if cart %}
            <h2>Your Shopping Cart</h5>
            <table style="width:100% ;">
                <thead style="background-color:black ;color: white">
                    <tr>
                        <th>Name</th>
                        <th>Unit Price</th>
                        <th>Total Price</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody style="background-color:rgb(163, 162, 162) ;">

                    {% for i in cart %}
                        <tr style="height: 55px">
                            <td>{{ i.product.name }}</td>
                            <td>{{ i.product.price }}</td>
                            <td>{{ i.t_price }}</td>
                            <td>
                                <div>
                                    <form action="{% url "products:cart_add" i.product.id %}" method="post">
                                        {{ i.quantity.quantity }}
                                        <input class="btn btn-outline-primary" type="submit" value="Update">
                                        {% csrf_token %}
                                    </form>
                                </div>
                            </td>
                            <td><a class="btn btn-primary" href="{% url "products:cart_remove" i.product.id %}">Remove</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <br>
            <h3>Grand Total = {{ grand_total }}</h3>
            <br>
            <a href="{% url 'products:cart_checkout' %}"><button>Checkout</button></a>
        {% else %}
            <h2>Your Shopping Cart Is Empty</h2>
        {% endif %}
        <a href="{% url 'products:listview' %}"><button>Continue shopping</button></a>
    </div>
{% endblock %}

Products/templates/Cart/Checkout.html
{% extends "MainPage.html" %}
{% load static %}
{% block content %}
    <div style="width:50%;text-align:center;background-color: #7d6969;margin:auto;padding:20px;">
        <h2>Checkout</h5>
            <a>The Total Bill Will Be {{ grand_total }}</a>
        <form method="POST">
            <table style="width:100% ;">
                <tbody style="background-color:rgb(163, 162, 162) ;">
                    <tr style="height: 55px">
                        <td>Name</td>
                        <td><input style="width: 80%;" type="text" name="customer" required ></td>
                    </tr>
                    <tr style="height: 55px">
                        <td>Address</td>
                        <td><input style="width: 80%;" type="text" name="address" required ></td>
                    </tr>
                    <tr style="height: 55px">
                        <td>Contact</td>
                        <td><input style="width: 80%;" type="text" name="contact" required ></td>
                    </tr>
                </tbody>
            </table>
            <button type="submit">Order</button>
            {% csrf_token %}
        </form>
    </div>
{% endblock %}