EComerce/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include("Products.urls", namespace = 'products')),
    path('auth/' , include("Authentication.urls", namespace = 'auth')),
]

Products/urls.py
from django.urls import path

from .views import *

app_name = 'Products'

urlpatterns = [
    path('' , ManageProductListView , name="listview" ),
    path('product/<id>' , ManageProductDetailView , name="detailview" ),
    path('category/' , ManageCategoryView , name="category" ),
    path('category/<id>' , ManageCategoryView , name="category" ),
    path('cart/<id>' , ManageAddToCartView , name="cart_add" ),
    path('my-cart/' , ManageCartDetailView , name="cart_detail" ),
    path('my-cart/remove/<id>' , ManageCartRemoveView , name="cart_remove" ),
    path('my-cart/checkout' , ManageCheckoutView , name="cart_checkout" ),
]

Products/models.py
from distutils.sysconfig import customize_compiler
from django.db import models


class Categories(models.Model):
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank = True, null=True)
    name = models.CharField(max_length = 50)
    slug = models.SlugField(max_length=200)
    class Meta:
        unique_together = ('slug', 'parent',)    
        verbose_name_plural = "categories"
    def __str__(self):
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' -> '.join(full_path[::-1])  

class Products(models.Model):
    name = models.CharField(max_length = 50)
    picture = models.URLField()
    category = models.ForeignKey(Categories , on_delete = models.PROTECT)
    price = models.IntegerField()
    available = models.BooleanField()
    def __str__(self):
        return self.name

class Order(models.Model):
    customer = models.CharField(max_length=50)
    address = models.CharField(max_length=500)
    contact = models.IntegerField()
    total_price = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.customer

class OrderProducts(models.Model):
    order = models.ForeignKey(Order , on_delete=models.PROTECT)
    product = models.ForeignKey(Products , on_delete=models.PROTECT)
    qty = models.IntegerField()
    unit_price = models.IntegerField()
    def __str__(self):
        return "{}".format(self.order)

Products/forms.py
from django import forms

from Products.models import Order, OrderProducts

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'customer',
            'address',
            'contact',
            'total_price',
        ]

class OrderProductsCreateForm(forms.ModelForm):
    class Meta:
        model = OrderProducts
        fields = [
            'order',
            'product',
            'qty',
            'unit_price',
        ]

Products/views.py
from itertools import product
from django.shortcuts import render , redirect , get_object_or_404
import time
from Products.models import Categories, Products
from .forms import *
from .cart import *

def get_category():
    v = []
    for i in Categories.objects.all():
        parent = []
        if not i.parent:
            ch1 = []
            for k in i.children.all():
                ch2 = []
                for p in k.children.all():
                    ch3 = []
                    for q in p.children.all():
                        ch4 = []
                        for r in q.children.all():
                            ch4.append({'name': r})
                        if ch4 is not []:
                            ch3.append({'name': q , 'children' : ch4})
                    if ch3 is not []:
                        ch2.append({'name':p , 'children' : ch3})
                if ch2 is not []:
                    ch1.append({'name':k,'children':ch2})
            parent.append({'name':i,'children':ch1})
            v.append(parent)
    return v

def ManageProductListView(ListView):
    products = Products.objects.all()
    context = {
        'categories' : get_category() ,
        'products' : products ,
    }
    return render(ListView , 'Product/List.html' , context)

def ManageProductDetailView(DetailView , id):
    product = get_object_or_404(Products , pk = id)
    context = {
        'categories' : get_category() ,
        'product' : product ,
    }
    return render(DetailView , 'Product/Detail.html' , context)

def ManageCategoryView(CategoryView , id = None):
    categories = Categories.objects.all()
    if id:
        products = Products.objects.all().filter(category = get_object_or_404(Categories , pk = id))
    else:
        try:
            products = Products.objects.all().filter(category = CategoryView.POST.get('category'))
        except:
            return redirect('products:listview')
    context = {
        'categories' : get_category() ,
        'products' : products ,
    }
    return render(CategoryView , 'Product/List.html' , context)

def ManageAddToCartView(AddView , id):
    cart = Cart(AddView)
    product = get_object_or_404(Products, pk=id)
    form = CartAddProductForm(AddView.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,quantity=cd['quantity'],update_quantity=cd['update'])
    time.sleep(1)
    return redirect('products:cart_detail',)

def ManageCartDetailView(DetailView):
    unorder_cart = Cart(DetailView)
    for item in unorder_cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
    cart = []
    for v in unorder_cart:
        quantity = (v.get('update_quantity_form'))
        t_price = (v.get('total_price'))
        price = (v.get('price'))
        product = (v.get('product'))
        cart.append({'product' : product , 'quantity' : quantity , 'price' : price , 't_price' : t_price })
    grand_total = (unorder_cart.get_total_price())
    context = {
        'cart': cart,
        'grand_total': grand_total,
    }
    return render(DetailView, 'Cart/Cart.html',context)

def ManageCartRemoveView(request, id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=id)
    cart.remove(product)
    return redirect('products:cart_detail')

def ManageCheckoutView(CheckoutView):
    unorder_cart = Cart(CheckoutView)
    if CheckoutView.method == 'POST':
        form = OrderCreateForm({
            'customer' : CheckoutView.POST.get('customer') ,
            'address' : CheckoutView.POST.get('address') ,
            'contact' : CheckoutView.POST.get('contact') ,
            'total_price' : unorder_cart.get_total_price() ,
        })
        order = form.save()
        for v in unorder_cart:
            quantity = (v.get('quantity'))
            price = (v.get('price'))
            product = (v.get('product'))
            form = OrderProductsCreateForm({
                'order' : order ,
                'product' : product ,
                'qty' : quantity ,
                'unit_price' : price ,
            })
            if form.is_valid:
                form.save()
        unorder_cart.clear()
        return redirect('products:cart_detail')
    else:
        grand_total = (unorder_cart.get_total_price())
        context = {
            'grand_total': grand_total,
        }
        return render(CheckoutView , 'Cart/Checkout.html' , context)

Products/templates/Product/Detail.html
{% extends 'MainPage.html' %}
{% block content %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        .dropdown-submenu {
            position: relative;
        }
        
        .dropdown-submenu .dropdown-menu {
            top: 0;
            left: 100%;
            margin-top: -1px;
        }
    </style>
    <div style="width:35%;text-align:center;background-color: #7d6969;margin:auto;padding:20px;">
        <div class="dropdown" style="width:min-content;">
            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Categories<span class="caret"></span></button>
            <ul class="dropdown-menu">
                {% for i in categories %}
                    {% for p in i %}
                        {% if not p.children %}
                            <li><a tabindex="-1" href="{% url 'products:category' p.name.pk %}">{{ p.name.name }}</a></li>
                        {% else %}
                            <li class="dropdown-submenu">
                                <a class="test" tabindex="-1" href="#">{{ p.name.name }} <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    {% for l in p.children %}
                                        {% if not l.children %}
                                            <li><a tabindex="-1" href="{% url 'products:category' l.name.pk %}">{{ l.name.name }}</a></li>
                                        {% else %}
                                            <li class="dropdown-submenu">
                                                <a class="test" tabindex="-1" href="#">{{ l.name.name }} <span class="caret"></span></a>
                                                <ul class="dropdown-menu">
                                                    {% for m in l.children %}
                                                        {% if not m.children %}
                                                            <li><a tabindex="-1" href="{% url 'products:category' m.name.pk %}">{{ m.name.name }}</a></li>
                                                        {% else %}
                                                            <li class="dropdown-submenu">
                                                                <a class="test" tabindex="-1" href="#">{{ m.name.name }} <span class="caret"></span></a>
                                                                <ul class="dropdown-menu">
                                                                    {% for n in m.children %}
                                                                        {% if not n.children %}
                                                                            <li><a tabindex="-1" href="{% url 'products:category' n.name.pk %}">{{ n.name.name }}</a></li>
                                                                        {% else %}
                                                                            <li class="dropdown-submenu">
                                                                                <a class="test" tabindex="-1" href="#">{{ n.name.name }} <span class="caret"></span></a>
                                                                                <ul class="dropdown-menu">
                                                                                    {% for o in n.children %}
                                                                                        <li><a tabindex="-1" href="{% url 'products:category' o.name.pk %}">{{ o.name.name }}</a></li>
                                                                                    {% endfor %}
                                                                                </ul>
                                                                            </li>
                                                                        {% endif %}
                                                                    {% endfor %}
                                                                </ul>
                                                            </li>
                                                        {% endif %}
                                                    {% endfor %}
                                                </ul>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
    </div>
    <br>
    <div style="background-color: #7d6969;text-align: center;width:50%;margin: auto;">
        <br>
        <h1>{{ product.name }}</h1>
        <img src="{{ product.picture }}" width="500px">
        <br>
        <br>
        <a><span style="font-weight:bold;font-size: 25px;">{{ product.price }}</span><span style="font-size:12px;"> COM</span></a>
        <br>
        <br>
        <a href="{% url 'products:category' product.category.pk %}">{{ product.category.name }}</a>
        <br>
        <br>
        <form action="{% url 'products:cart_add' product.pk %}" method="POST">
            <select name="quantity" required>
                <option value="">Select QTY</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
            </select>
            <button>Add To Cart</button>
            {% csrf_token %}
        </form>
        <br>
        <br>
    </div>
    <br>
    <br>
    <br>
    <br>
    <script>
        $(document).ready(function(){
          $('.dropdown-submenu a.test').on("click", function(e){
            $(this).next('ul').toggle();
            e.stopPropagation();
            e.preventDefault();
          });
        });
    </script>
{% endblock %}

Products/templates/Product/List.html
{% extends 'MainPage.html' %}
{% block content %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        .dropdown-submenu {
            position: relative;
        }
        
        .dropdown-submenu .dropdown-menu {
            top: 0;
            left: 100%;
            margin-top: -1px;
        }
    </style>
    <div style="width:35%;text-align:center;background-color: #7d6969;margin:auto;padding:20px;">
        <div class="dropdown" style="width:min-content;">
            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Categories<span class="caret"></span></button>
            <ul class="dropdown-menu">
                {% for i in categories %}
                    {% for p in i %}
                        {% if not p.children %}
                            <li><a tabindex="-1" href="{% url 'products:category' p.name.pk %}">{{ p.name.name }}</a></li>
                        {% else %}
                            <li class="dropdown-submenu">
                                <a class="test" tabindex="-1" href="#">{{ p.name.name }} <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    {% for l in p.children %}
                                        {% if not l.children %}
                                            <li><a tabindex="-1" href="{% url 'products:category' l.name.pk %}">{{ l.name.name }}</a></li>
                                        {% else %}
                                            <li class="dropdown-submenu">
                                                <a class="test" tabindex="-1" href="#">{{ l.name.name }} <span class="caret"></span></a>
                                                <ul class="dropdown-menu">
                                                    {% for m in l.children %}
                                                        {% if not m.children %}
                                                            <li><a tabindex="-1" href="{% url 'products:category' m.name.pk %}">{{ m.name.name }}</a></li>
                                                        {% else %}
                                                            <li class="dropdown-submenu">
                                                                <a class="test" tabindex="-1" href="#">{{ m.name.name }} <span class="caret"></span></a>
                                                                <ul class="dropdown-menu">
                                                                    {% for n in m.children %}
                                                                        {% if not n.children %}
                                                                            <li><a tabindex="-1" href="{% url 'products:category' n.name.pk %}">{{ n.name.name }}</a></li>
                                                                        {% else %}
                                                                            <li class="dropdown-submenu">
                                                                                <a class="test" tabindex="-1" href="#">{{ n.name.name }} <span class="caret"></span></a>
                                                                                <ul class="dropdown-menu">
                                                                                    {% for o in n.children %}
                                                                                        <li><a tabindex="-1" href="{% url 'products:category' o.name.pk %}">{{ o.name.name }}</a></li>
                                                                                    {% endfor %}
                                                                                </ul>
                                                                            </li>
                                                                        {% endif %}
                                                                    {% endfor %}
                                                                </ul>
                                                            </li>
                                                        {% endif %}
                                                    {% endfor %}
                                                </ul>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
    </div>
    <div style="background-color: #e5de7c;text-align: center;width:75%;margin: auto;">
        {% for i in products %}
            <div style="background-color: #7d6969;float: left;width:300px;padding:20px;margin:10px;text-align: center;">
                <h2>{{ i.name }}</h2>
                <a style="color:#000000;" href="{% url 'products:detailview' i.pk %}"><img src="{{ i.picture }}" width="200px"></a>
                <br>
                <a style="color:#000000;"><span style="font-weight:bold">{{ i.price }}</span><span style="font-size:12px;"> COM</span></a>
                <br>
                <a style="color:#000000;">{{ i.category.name }} {{ i.category.parent.name }}</a>
            </div>
        {% endfor %}
    </div>
    <script>
        $(document).ready(function(){
          $('.dropdown-submenu a.test').on("click", function(e){
            $(this).next('ul').toggle();
            e.stopPropagation();
            e.preventDefault();
          });
        });
    </script>
{% endblock %}